name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 12 点自动运行
  workflow_dispatch:  # 也可以手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # 不使用默认的 GitHub 令牌
          fetch-depth: 0  # 完整克隆历史

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/original-owner/original-repo.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main

      - name: Push changes to your forked repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
